name: Run tests
on: [ push ]
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/test.txt --upgrade pip
      - name: Run tests
        run: coverage run -m pytest tests --junitxml="reports/junit.xml"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'reports/junit.xml'
      - name: Run coverage
        run: coverage xml -o reports/coverage.xml --omit="tests/*"
      - name: Publish Coverage Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: reports/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports
